<?xml version="1.0"?>
<!--
Software License Agreement (BSD)
  
\file      husky.urdf.xacro
\authors   Paul Bovbel <pbovbel@clearpathrobotics.com>, Devon Ash <dash@clearpathrobotics.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="husky" xmlns:xacro="http://ros.org/wiki/xacro"> <!-- Root elemen robot, nama unik -->

  <!-- ==================== ARGUMEN XACRO (FULL OOP) ==================== -->
  <xacro:arg name="imu_xyz" default="$(optenv HUSKY_IMU_XYZ 0.19 0 0.149)"/> <!-- Posisi IMU relatif parent -->
  <xacro:arg name="imu_rpy" default="$(optenv HUSKY_IMU_RPY 0 -1.5708 3.1416)"/> <!-- Orientasi IMU -->
  <xacro:arg name="imu_parent" default="$(optenv HUSKY_IMU_PARENT base_link)"/> <!-- Parent link IMU -->

  <xacro:arg name="laser_enabled" default="$(optenv HUSKY_LMS1XX_ENABLED 0)" />
  <xacro:arg name="laser_topic" default="$(optenv HUSKY_LMS1XX_TOPIC front/scan)"/>
  <xacro:arg name="laser_tower" default="$(optenv HUSKY_LMS1XX_TOWER 1)"/>
  <xacro:arg name="laser_prefix" default="$(optenv HUSKY_LMS1XX_PREFIX front)"/>
  <xacro:arg name="laser_parent" default="$(optenv HUSKY_LMS1XX_PARENT top_plate_link)"/>
  <xacro:arg name="laser_xyz" default="$(optenv HUSKY_LMS1XX_XYZ 0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_rpy" default="$(optenv HUSKY_LMS1XX_RPY 0.0 0.0 0.0)" />

  <xacro:arg name="laser_secondary_enabled" default="$(optenv HUSKY_LMS1XX_SECONDARY_ENABLED 0)" />
  <xacro:arg name="laser_secondary_topic" default="$(optenv HUSKY_LMS1XX_SECONDARY_TOPIC rear/scan)"/>
  <xacro:arg name="laser_secondary_tower" default="$(optenv HUSKY_LMS1XX_SECONDARY_TOWER 1)"/>
  <xacro:arg name="laser_secondary_prefix" default="$(optenv HUSKY_LMS1XX_SECONDARY_PREFIX rear)"/>
  <xacro:arg name="laser_secondary_parent" default="$(optenv HUSKY_LMS1XX_SECONDARY_PARENT top_plate_link)"/>
  <xacro:arg name="laser_secondary_xyz" default="$(optenv HUSKY_LMS1XX_SECONDARY_XYZ -0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_secondary_rpy" default="$(optenv HUSKY_LMS1XX_SECONDARY_RPY 0.0 0.0 3.14159)" />

  <xacro:arg name="laser_ust10_front_enabled" default="$(optenv HUSKY_UST10_ENABLED 0)" />
  <xacro:arg name="laser_ust10_front_topic" default="$(optenv HUSKY_UST10_TOPIC front/scan)" />
  <xacro:arg name="laser_ust10_front_prefix" default="$(optenv HUSKY_UST10_PREFIX front)" />
  <xacro:arg name="laser_ust10_front_parent" default="$(optenv HUSKY_UST10_PARENT top_plate_link)" />
  <xacro:arg name="laser_ust10_front_xyz" default="$(optenv HUSKY_UST10_XYZ 0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_ust10_front_rpy" default="$(optenv HUSKY_UST10_RPY 0 0 0)" />

  <xacro:arg name="laser_ust10_rear_enabled" default="$(optenv HUSKY_UST10_SECONDARY_ENABLED 0)" />
  <xacro:arg name="laser_ust10_rear_topic" default="$(optenv HUSKY_UST10_SECONDARY_TOPIC rear/scan)" />
  <xacro:arg name="laser_ust10_rear_prefix" default="$(optenv HUSKY_UST10_SECONDARY_PREFIX rear)" />
  <xacro:arg name="laser_ust10_rear_parent" default="$(optenv HUSKY_UST10_SECONDARY_PARENT top_plate_link)" />
  <xacro:arg name="laser_ust10_rear_xyz" default="$(optenv HUSKY_UST10_SECONDARY_XYZ -0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_ust10_rear_rpy" default="$(optenv HUSKY_UST10_SECONDARY_RPY 0 0 3.14159)" />

  <xacro:arg name="laser_3d_enabled" default="$(optenv HUSKY_LASER_3D_ENABLED 0)" />
  <xacro:arg name="laser_3d_topic" default="$(optenv HUSKY_LASER_3D_TOPIC points)"/>
  <xacro:arg name="laser_3d_tower" default="$(optenv HUSKY_LASER_3D_TOWER 1)"/>
  <xacro:arg name="laser_3d_prefix" default="$(optenv HUSKY_LASER_3D_PREFIX )"/>
  <xacro:arg name="laser_3d_parent" default="$(optenv HUSKY_LASER_3D_PARENT top_plate_link)"/>
  <xacro:arg name="laser_3d_xyz" default="$(optenv HUSKY_LASER_3D_XYZ 0 0 0)" />
  <xacro:arg name="laser_3d_rpy" default="$(optenv HUSKY_LASER_3D_RPY 0 0 0)" />

  <xacro:arg name="laser_3d_secondary_enabled" default="$(optenv HUSKY_LASER_3D_SECONDARY_ENABLED 0)" />
  <xacro:arg name="laser_3d_secondary_topic" default="$(optenv HUSKY_LASER_3D_SECONDARY_TOPIC secondary_points)"/>
  <xacro:arg name="laser_3d_secondary_tower" default="$(optenv HUSKY_LASER_3D_SECONDARY_TOWER 1)"/>
  <xacro:arg name="laser_3d_secondary_prefix" default="$(optenv HUSKY_LASER_3D_SECONDARY_PREFIX secondary_)"/>
  <xacro:arg name="laser_3d_secondary_parent" default="$(optenv HUSKY_LASER_3D_SECONDARY_PARENT top_plate_link)"/>
  <xacro:arg name="laser_3d_secondary_xyz" default="$(optenv HUSKY_LASER_3D_SECONDARY_XYZ 0 0 0)" />
  <xacro:arg name="laser_3d_secondary_rpy" default="$(optenv HUSKY_LASER_3D_SECONDARY_RPY 0 0 -3.14159)" />

  <xacro:arg name="realsense_enabled" default="$(optenv HUSKY_REALSENSE_ENABLED 0)" />
  <xacro:arg name="realsense_model" default="$(optenv HUSKY_REALSENSE_MODEL d435)"/>
  <xacro:arg name="realsense_topic" default="$(optenv HUSKY_REALSENSE_TOPIC realsense)" />
  <xacro:arg name="realsense_prefix" default="$(optenv HUSKY_REALSENSE_PREFIX camera)" />
  <xacro:arg name="realsense_parent" default="$(optenv HUSKY_REALSENSE_PARENT top_plate_link)" />
  <xacro:arg name="realsense_xyz" default="$(optenv HUSKY_REALSENSE_XYZ 0 0 0)" />
  <xacro:arg name="realsense_rpy" default="$(optenv HUSKY_REALSENSE_RPY 0 0 0)" />
  <xacro:property name="realsense_model" value="$(arg realsense_model)"/>

  <xacro:arg name="realsense_secondary_enabled" default="$(optenv HUSKY_REALSENSE_SECONDARY_ENABLED 0)" />
  <xacro:arg name="realsense_secondary_model" default="$(optenv HUSKY_REALSENSE_SECONDARY_MODEL d435)"/>
  <xacro:arg name="realsense_secondary_topic" default="$(optenv HUSKY_REALSENSE_SECONDARY_TOPIC realsense_secondary)" />
  <xacro:arg name="realsense_secondary_prefix" default="$(optenv HUSKY_REALSENSE_SECONDARY_PREFIX camera_secondary)" />
  <xacro:arg name="realsense_secondary_parent" default="$(optenv HUSKY_REALSENSE_SECONDARY_PARENT top_plate_link)" />
  <xacro:arg name="realsense_secondary_xyz" default="$(optenv HUSKY_REALSENSE_SECONDARY_XYZ 0 0 0)" />
  <xacro:arg name="realsense_secondary_rpy" default="$(optenv HUSKY_REALSENSE_SECONDARY_RPY 0 0 0)" />
  <xacro:property name="realsense_secondary_model" value="$(arg realsense_secondary_model)"/>

  <xacro:arg name="blackfly_enabled" default="$(optenv HUSKY_BLACKFLY 0)"/>
  <xacro:arg name="blackfly_mount_enabled" default="$(optenv HUSKY_BLACKFLY_MOUNT_ENABLED 1)"/>
  <xacro:arg name="blackfly_mount_angle" default="$(optenv HUSKY_BLACKFLY_MOUNT_ANGLE 0)"/>
  <xacro:arg name="blackfly_prefix" default="$(optenv HUSKY_BLACKFLY_PREFIX blackfly)"/>
  <xacro:arg name="blackfly_parent" default="$(optenv HUSKY_BLACKFLY_PARENT top_plate_link)"/>
  <xacro:arg name="blackfly_xyz" default="$(optenv HUSKY_BLACKFLY_XYZ 0 0 0)"/>
  <xacro:arg name="blackfly_rpy" default="$(optenv HUSKY_BLACKFLY_RPY 0 0 0)"/>

  <xacro:arg name="blackfly_secondary_enabled" default="$(optenv HUSKY_BLACKFLY_SECONDARY 0)"/>
  <xacro:arg name="blackfly_secondary_mount_enabled" default="$(optenv HUSKY_BLACKFLY_SECONDARY_MOUNT_ENABLED 1)"/>
  <xacro:arg name="blackfly_secondary_mount_angle" default="$(optenv HUSKY_BLACKFLY_SECONDARY_MOUNT_ANGLE 0)"/>
  <xacro:arg name="blackfly_secondary_prefix" default="$(optenv HUSKY_BLACKFLY_SECONDARY_PREFIX blackfly_secondary)"/>
  <xacro:arg name="blackfly_secondary_parent" default="$(optenv HUSKY_BLACKFLY_SECONDARY_PARENT top_plate_link)"/>
  <xacro:arg name="blackfly_secondary_xyz" default="$(optenv HUSKY_BLACKFLY_SECONDARY_XYZ 0 0 0)"/>
  <xacro:arg name="blackfly_secondary_rpy" default="$(optenv HUSKY_BLACKFLY_SECONDARY_RPY 0 0 0)"/>

  <xacro:property name="husky_front_bumper_extend" value="$(optenv HUSKY_FRONT_BUMPER_EXTEND 0)" />
  <xacro:property name="husky_rear_bumper_extend" value="$(optenv HUSKY_REAR_BUMPER_EXTEND 0)" />

  <xacro:arg name="sensor_arch" default="$(optenv HUSKY_SENSOR_ARCH 0)" />
  <xacro:arg name="sensor_arch_height" default="$(optenv HUSKY_SENSOR_ARCH_HEIGHT 510)" />
  <xacro:arg name="sensor_arch_xyz" default="$(optenv HUSKY_SENSOR_ARCH_OFFSET 0 0 0)"/>
  <xacro:arg name="sensor_arch_rpy" default="$(optenv HUSKY_SENSOR_ARCH_RPY 0 0 0)"/>

  <xacro:arg name="robot_namespace" default="$(optenv ROBOT_NAMESPACE /)" />
  <xacro:arg name="urdf_extras" default="$(optenv HUSKY_URDF_EXTRAS empty.urdf)" />
  <xacro:arg name="cpr_urdf_extras" default="$(optenv CPR_URDF_EXTRAS empty.urdf)" />

  <xacro:arg name="outdoornav_enabled" default="$(optenv OUTDOORNAV_ENABLED 0)" />
  <xacro:arg name="outdoornav_configuration" default="$(optenv OUTDOORNAV_CONFIGURATION standard)" />

  <!-- ==================== INCLUDE MACRO & PROPERTY ==================== -->
  <!-- Semua macro sensor dan dekorasi di-include agar bisa dipanggil OOP -->
  <xacro:include filename="$(find husky_description)/urdf/accessories/hokuyo_ust10.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/intel_realsense.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/flir_blackfly_mount.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/sensor_arch.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/sick_lms1xx_mount.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/vlp16_mount.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/decorations.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/wheel.urdf.xacro"/>

  <!-- ==================== PROPERTY UKURAN & PARAMETER ==================== -->
  <!-- Semua property ukuran dan parameter utama robot -->
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="base_x_size" value="0.98740000"/>
  <xacro:property name="base_y_size" value="0.57090000"/>
  <xacro:property name="base_z_size" value="0.24750000"/>
  <xacro:property name="wheelbase" value="0.5120"/>
  <xacro:property name="track" value="0.5708"/>
  <xacro:property name="wheel_vertical_offset" value="0.03282"/>
  <xacro:property name="wheel_length" value="0.1143"/>
  <xacro:property name="wheel_radius" value="0.1651"/>

  <!-- ==================== BASE LINK & FOOTPRINT ==================== -->
  <link name="base_link"> <!-- Link utama base robot -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://husky_description/meshes/base_link.dae"/> <!-- Mesh visual base -->
      </geometry>
    </visual>
    <collision>
      <origin xyz="${(husky_front_bumper_extend - husky_rear_bumper_extend)/2.0} 0 ${base_z_size/4}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size + husky_front_bumper_extend + husky_rear_bumper_extend} ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
      </geometry>
    </collision>
  </link>
  <link name="base_footprint"/> <!-- Link untuk navigasi 2D -->
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_footprint"/>
  </joint>

  <!-- ==================== INERTIAL LINK ==================== -->
  <link name="inertial_link">
    <inertial>
      <mass value="46.034"/>
      <origin xyz="-0.00065 -0.085 0.062"/>
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296"/>
    </inertial>
  </link>
  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="inertial_link"/>
  </joint>

  <!-- ==================== RODA (MACRO OOP) ==================== -->
  <!-- Semua roda pakai macro agar OOP dan mudah diubah -->
  <xacro:husky_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:husky_wheel>

  <!-- ==================== DEKORASI ==================== -->
  <xacro:husky_decorate/> <!-- Macro dekorasi visual -->

  <!-- ==================== SENSOR ARCH (OPSIONAL) ==================== -->
  <xacro:if value="$(arg sensor_arch)">
    <xacro:sensor_arch prefix="" parent="top_plate_link" size="$(arg sensor_arch_height)">
      <origin xyz="$(arg sensor_arch_xyz)" rpy="$(arg sensor_arch_rpy)"/>
    </xacro:sensor_arch>
  </xacro:if>

  <!-- ==================== IMU (FULL OOP) ==================== -->
  <link name="imu_link"/> <!-- Link IMU -->
  <joint name="imu_joint" type="fixed">
    <origin xyz="$(arg imu_xyz)" rpy="$(arg imu_rpy)"/>
    <parent link="$(arg imu_parent)"/>
    <child link="imu_link"/>
  </joint>
  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>50</update_rate>
      <plugin name="imu_sensor_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <namespace>$(arg robot_namespace)</namespace>
        </ros>
        <frame_name>imu_link</frame_name>
        <topicName>imu/data</topicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== SICK LMS1XX (OOP, Macro) ==================== -->
  <xacro:if value="$(arg laser_enabled)">
    <xacro:sick_lms1xx_mount prefix="$(arg laser_prefix)" parent="$(arg laser_parent)" topic="$(arg laser_topic)" robot_namespace="$(arg robot_namespace)" tower="$(arg laser_tower)">
      <origin xyz="$(arg laser_xyz)" rpy="$(arg laser_rpy)"/>
    </xacro:sick_lms1xx_mount>
  </xacro:if>
  <xacro:if value="$(arg laser_secondary_enabled)">
    <xacro:sick_lms1xx_mount prefix="$(arg laser_secondary_prefix)" parent="$(arg laser_secondary_parent)" topic="$(arg laser_secondary_topic)" robot_namespace="$(arg robot_namespace)" tower="$(arg laser_secondary_tower)">
      <origin xyz="$(arg laser_secondary_xyz)" rpy="$(arg laser_secondary_rpy)"/>
    </xacro:sick_lms1xx_mount>
  </xacro:if>

  <!-- ==================== HOKUYO UST10 (OOP, Macro) ==================== -->
  <xacro:if value="$(arg laser_ust10_front_enabled)">
    <xacro:hokuyo_ust10_mount topic="$(arg laser_ust10_front_topic)" prefix="$(arg laser_ust10_front_prefix)" parent_link="$(arg laser_ust10_front_parent)">
      <origin xyz="$(arg laser_ust10_front_xyz)" rpy="$(arg laser_ust10_front_rpy)"/>
    </xacro:hokuyo_ust10_mount>
  </xacro:if>
  <xacro:if value="$(arg laser_ust10_rear_enabled)">
    <xacro:hokuyo_ust10_mount topic="$(arg laser_ust10_rear_topic)" prefix="$(arg laser_ust10_rear_prefix)" parent_link="$(arg laser_ust10_rear_parent)">
      <origin xyz="$(arg laser_ust10_rear_xyz)" rpy="$(arg laser_ust10_rear_rpy)"/>
    </xacro:hokuyo_ust10_mount>
  </xacro:if>

  <!-- ==================== REALSENSE & BLACKFLY (OOP, Macro) ==================== -->
  <!-- Macro kamera, bisa diaktifkan via argumen -->
  <xacro:property name="realsense_enabled" value="$(arg realsense_enabled)"/>
  <xacro:property name="realsense_secondary_enabled" value="$(arg realsense_secondary_enabled)"/>
  <xacro:if value="${realsense_enabled or realsense_secondary_enabled}">
    <xacro:if value="${realsense_model == 'd435'}">
      <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>
    </xacro:if>
    <xacro:if value="${realsense_model == 'd435i'}">
      <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro"/>
    </xacro:if>
    <xacro:if value="${realsense_model == 'd415'}">
      <xacro:include filename="$(find realsense2_description)/urdf/_d415.urdf.xacro"/>
    </xacro:if>
    <xacro:if value="${realsense_model == 'd455'}">
      <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>
    </xacro:if>
  </xacro:if>

  <xacro:if value="$(arg realsense_enabled)">
    <xacro:realsense_sensor rs_model="$(arg realsense_model)"
                            prefix="$(arg realsense_prefix)"
                            parent="$(arg realsense_parent)"
                            topic="$(arg realsense_topic)"
                            include="0">
      <origin xyz="$(arg realsense_xyz)" rpy="$(arg realsense_rpy)"/>
    </xacro:realsense_sensor>
  </xacro:if>

  <xacro:if value="$(arg realsense_secondary_enabled)">
    <xacro:realsense_sensor rs_model="$(arg realsense_secondary_model)"
                            prefix="$(arg realsense_secondary_prefix)"
                            parent="$(arg realsense_secondary_parent)"
                            topic="$(arg realsense_secondary_topic)"
                            include="0">
      <origin xyz="$(arg realsense_secondary_xyz)" rpy="$(arg realsense_secondary_rpy)"/>
    </xacro:realsense_sensor>
  </xacro:if>

  <xacro:if value="$(arg blackfly_enabled)">
    <xacro:flir_blackfly_mount prefix="$(arg blackfly_prefix)"
                                parent="$(arg blackfly_parent)"
                                mount_enabled="$(arg blackfly_mount_enabled)"
                                mount_angle="$(arg blackfly_mount_angle)">
      <origin xyz="$(arg blackfly_xyz)" rpy="$(arg blackfly_rpy)"/>
    </xacro:flir_blackfly_mount>
  </xacro:if>

  <xacro:if value="$(arg blackfly_secondary_enabled)">
    <xacro:flir_blackfly_mount prefix="$(arg blackfly_secondary_prefix)"
                                parent="$(arg blackfly_secondary_parent)"
                                mount_enabled="$(arg blackfly_secondary_mount_enabled)"
                                mount_angle="$(arg blackfly_secondary_mount_angle)">
      <origin xyz="$(arg blackfly_secondary_xyz)" rpy="$(arg blackfly_secondary_rpy)"/>
    </xacro:flir_blackfly_mount>
  </xacro:if>

  <!-- ==================== VLP16 LIDAR (OOP, Macro) ==================== -->
  <xacro:if value="$(arg laser_3d_enabled)">
    <xacro:if value="$(arg laser_3d_tower)">
      <xacro:vlp16_mount prefix="$(arg laser_3d_prefix)" parent_link="$(arg laser_3d_parent)" topic="$(arg laser_3d_topic)">
        <origin xyz="$(arg laser_3d_xyz)" rpy="$(arg laser_3d_rpy)"/>
      </xacro:vlp16_mount>
    </xacro:if>
    <xacro:unless value="$(arg laser_3d_tower)">
      <xacro:VLP-16 parent="$(arg laser_3d_parent)" topic="$(arg laser_3d_topic)" name="$(arg laser_3d_prefix)velodyne">
        <origin xyz="$(arg laser_3d_xyz)" rpy="$(arg laser_3d_rpy)"/>
      </xacro:VLP-16>
    </xacro:unless>
  </xacro:if>

  <xacro:if value="$(arg laser_3d_secondary_enabled)">
    <xacro:if value="$(arg laser_3d_secondary_tower)">
      <xacro:vlp16_mount prefix="$(arg laser_3d_secondary_prefix)" parent_link="$(arg laser_3d_secondary_parent)" topic="$(arg laser_3d_secondary_topic)">
        <origin xyz="$(arg laser_3d_secondary_xyz)" rpy="$(arg laser_3d_secondary_rpy)"/>
      </xacro:vlp16_mount>
    </xacro:if>
    <xacro:unless value="$(arg laser_3d_secondary_tower)">
      <xacro:VLP-16 parent="$(arg laser_3d_secondary_parent)" topic="$(arg laser_3d_secondary_topic)" name="$(arg laser_3d_secondary_prefix)velodyne">
        <origin xyz="$(arg laser_3d_secondary_xyz)" rpy="$(arg laser_3d_secondary_rpy)"/>
      </xacro:VLP-16>
    </xacro:unless>
  </xacro:if>

  <!-- ==================== OUTDOORNAV (OPSIONAL) ==================== -->
  <xacro:if value="$(arg outdoornav_enabled)">
    <xacro:include filename="$(find cpr_onav_description)/urdf/outdoornav_description.urdf.xacro"/>
    <xacro:outdoornav_sensors outdoornav_configuration="$(arg outdoornav_configuration)"/>
  </xacro:if>

  <!-- ==================== TAG ros2_control (WAJIB) ==================== -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- ==================== PLUGIN GAZEBO (ros2_control) ==================== -->
  <!-- 
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros_control">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <robotParam>/robot_description</robotParam>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo> 
  -->

  <!-- ==================== PLUGIN GPS (REVISI: GANTI KE ROS2 NATIVE) ==================== -->
  <gazebo reference="gps_link">
    <sensor type="gps" name="gps_sensor">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <plugin name="gps_sensor_plugin" filename="libgazebo_ros_gps_sensor.so">
        <ros>
          <namespace>$(arg robot_namespace)</namespace>
        </ros>
        <frame_name>gps_link</frame_name>
        <topicName>gps/fix</topicName>
        <velocityTopicName>gps/vel</velocityTopicName>
      </plugin>
    </sensor>
  </gazebo>
  <link name="gps_link"/> <!-- Link GPS, hanya boleh ada satu di seluruh workspace! -->
  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
  </joint>

  <!-- ==================== CUSTOM INCLUDE (OPSIONAL) ==================== -->
  <xacro:include filename="$(arg urdf_extras)"/>
  <xacro:include filename="$(arg cpr_urdf_extras)"/>

</robot>