multicam_yolo:
  ros__parameters:
    cam_count: 6
    cam_center: 133
    fov_h: 85.0
    view_p: 0.30
    view_h: 0.30
    segmentation_model: "yolo12x.engine"
    camera_topics:
      - '/camera_front/image_raw'
      - '/camera_right/image_raw'
      - '/camera_rear_right/image_raw'
      - '/camera_rear/image_raw'
      - '/camera_left/image_raw'
      - '/camera_front_left/image_raw'